// This file was automatically generated by the amba-fbd tool.
// https://github.com/Functional-Bus-Description-Language/amba-fbd

#ifndef _AFBD_AMBA_FBD_H_
#define _AFBD_AMBA_FBD_H_

#if defined(__KERNEL__) && defined(__linux__)
	#include <linux/types.h>
#else
	#include <stddef.h>
	#include <stdint.h>
#endif

typedef struct amba_fbd_iface amba_fbd_iface_t;

struct amba_fbd_iface {
	// Single read, should return negative values in case of errors.
	int (*read)(amba_fbd_iface_t *const iface, const uintptr_t addr, uint{{.BusWidth}}_t *const data);
	// Single write, should return negative values in case of errors.
	int (*write)(amba_fbd_iface_t *const iface, const uintptr_t addr, const uint{{.BusWidth}}_t data);
	// Block read, returns number of read words, or negative value in case of errors.
	int (*readb)(amba_fbd_iface_t *const iface, const uintptr_t addr, uint{{.BusWidth}}_t *buf, size_t count);
	// Block write, returns number of written words, or negative value in case of errors.
	int (*writeb)(amba_fbd_iface_t *const iface, const uintptr_t addr, const uint{{.BusWidth}}_t *buf, size_t count);
	// Optional custom data used as required to implement the interface.
	// For example, a memory-mapped interface may store memory pointer here.
	void *data;
};

#define amba_fbd_read(elem, data) (amba_fbd_ ## elem ## _read(AMBA_FBD_IFACE, data))
#define amba_fbd_write(elem, data) (amba_fbd_ ## elem ## _write(AMBA_FBD_IFACE, data))

#ifdef AFBD_SHORT_MACROS
	#undef amba_fbd_read
	#undef amba_fbd_write
	#define read(elem, data) (amba_fbd_ ## elem ## _read(AMBA_FBD_IFACE, data))
	#define write(elem, data) (amba_fbd_ ## elem ## _write(AMBA_FBD_IFACE, data))
#endif

#endif // _AFBD_AMBA_FBD_H_
