// This file was automatically generated by the amba-fbd tool.
// https://github.com/Functional-Bus-Description-Language/amba-fbd

#ifndef _AFBD_MMAP_IFACE_H_
#define _AFBD_MMAP_IFACE_H_

#if defined(__KERNEL__)
	#include <linux/types.h>
#else
	#include <stddef.h>
	#include <stdint.h>
#endif

#include "amba_fbd.h"

// Initializes are returns amba_fbd interface.
// iomem is a pointer to the memory-mapped IO (registers).
amba_fbd_iface_t amba_fbd_linux_mmap_iface(void *const iomem);

#endif // _AFBD_MMAP_IFACE_H_
