// This file was automatically generated by the amba-fbd tool.
// https://github.com/Functional-Bus-Description-Language/amba-fbd

#if defined(__KERNEL__)
	#include <linux/io.h>
#else
	#include <stdatomic.h>
#endif

#include "linux-mmap-iface.h"

static int amba_fbd_linux_mmap_iface_read(amba_fbd_iface_t *const iface, const uintptr_t addr, uint{{.BusWidth}}_t *const data)
{
#if defined(__KERNEL__)
	*data = ioread{{.BusWidth}}((uint{{.BusWidth}}_t __iomem *)iface->data + addr);
#else
	*data = atomic_load((volatile _Atomic uint{{.BusWidth}}_t*)iface->data + addr);
#endif
	return 0;
}

static int amba_fbd_linux_mmap_iface_write(amba_fbd_iface_t *const iface, const uintptr_t addr, const uint{{.BusWidth}}_t data)
{
#if defined(__KERNEL__)
	iowrite{{.BusWidth}}(data, (uint{{.BusWidth}}_t __iomem *)iface->data + addr);
#else
	atomic_store((volatile _Atomic uint{{.BusWidth}}_t*)iface->data + addr, data);
#endif
	return 0;
}

static int amba_fbd_linux_mmap_iface_readb(amba_fbd_iface_t *const iface, const uintptr_t addr, uint{{.BusWidth}}_t *buf, size_t count)
{
	for (size_t i = 0; i < count; i++)
		iface->read(iface, addr + i, &buf[i]);

	return count;
}

static int amba_fbd_linux_mmap_iface_writeb(amba_fbd_iface_t *const iface, const uintptr_t addr, const uint{{.BusWidth}}_t *buf, size_t count)
{
	for (size_t i = 0; i < count; i++)
		iface->write(iface, addr + i, buf[i]);

	return count;
}

amba_fbd_iface_t amba_fbd_linux_mmap_iface(void *const iomem)
{
	return (amba_fbd_iface_t){
		read: amba_fbd_linux_mmap_iface_read,
		write: amba_fbd_linux_mmap_iface_write,
		readb: amba_fbd_linux_mmap_iface_readb,
		writeb: amba_fbd_linux_mmap_iface_writeb,
		data: iomem
	};
}
